site_name: 善知鸟跨境ERP文档
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed

nav:
  - 产品介绍: 
    - 善知鸟ERP介绍: index.md
  - 功能介绍: 
    - Listing管理: listing/product.md
    - 货代管理: fba/index.md
    - FBA头程: fba/index.md
    - 供应商管理: supplier/supply.md
    - 采购管理: supplier/index.md

  - 联系作者: about/contact.md