site_name: 善知鸟跨境ERP文档
theme:
  name: material
  custom_dir: overrides
  logo: assets/puffin-logo2.png
  palette:
    primary: indigo
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed

nav:
  - 产品介绍: 
    - 善知鸟跨境ERP介绍: index.md
  - 操作说明: 
    - 亚马逊店铺授权: amz-store/api-conf.md
    - Listing管理: listing/sync-listing.md
    - 货代管理: carrier/index.md
    - FBA头程: fba/index.md
    - 供应商管理: supplier/supply.md
    - 采购管理: supplier/purchase.md
  - 改进反馈: feedback/index.md
  - 技术架构:
    - 架构: arch/index.md 
  - 定价信息: pricing/index.md

  - 联系作者: about/contact.md
  - 数据可视化分析: data-ansys/index.md
  - 其它IT服务: it-service/index.md